version: 2.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: 050eKctkQvknlaXWi3kQY0u/H8dfNN3NWXaaoRi5L+tWUYfOaD59Ezp0IhycjXKA

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017 RC
  
configuration: Release

before_build:
- ps: . .\patch-version.ps1 "src\sendstorm\sendstorm.csproj"

build_script:
- msbuild /t:Restore /p:Configuration=%CONFIGURATION% src\sendstorm.sln
- msbuild /t:Build /p:Configuration=%CONFIGURATION% src\sendstorm.sln

after_build:
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\..\artifacts src\sendstorm\sendstorm.csproj

test_script:
- ps: . .\set-debug-type.ps1 "src\sendstorm\sendstorm.csproj"
- dotnet test src\sendstorm.tests\sendstorm.tests.csproj  -f net45 -c %CONFIGURATION% --no-build
- dotnet test src\sendstorm.tests\sendstorm.tests.csproj  -f netcoreapp1.0 -c %CONFIGURATION% --no-build
- ps: . .\coverage.ps1

artifacts:
- path: artifacts\Sendstorm.*.nupkg
  name: NuGet

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true