version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true
  
configuration: Release

assembly_info:
  patch: true
  file: 'src\netcore\**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
before_build:
- nuget restore src\netcore\sendstorm.core.sln

build:
  project: src\netcore\sendstorm.core.sln
  parallel: true
  verbosity: normal
  
after_build:
- nuget pack src\netcore\src\sendstorm.core.csproj -Properties "Configuration=Release;Platform=AnyCPU" -IncludeReferencedProjects
  
test:
  assemblies:
  - 'src\netcore\**\*.Tests.dll'
  
artifacts:
- path: Sendstorm.*.nupkg
  name: Nuget Package

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true