version: 1.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: 050eKctkQvknlaXWi3kQY0u/H8dfNN3NWXaaoRi5L+tWUYfOaD59Ezp0IhycjXKA
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore src\sendstorm.sln
build:
  publish_nuget: true
  publish_nuget_symbols: false
  include_nuget_references: true
  parallel: true
  verbosity: normal
test_script:
- ps: coverage.ps1
notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true